# title: Savitha Ravi
# logo: "/images/headshot.jpg?raw=true" # your photo (or logo) here
# description: > # your text below (remove <br> elements if you don't need line breaks)
#   Ph.D. student at UC San Diego
#   <br><br>


locale                   : "en-US"
title                    : "Savitha Ravi"
title_separator          : "-"
name                     : &name "Savitha Ravi"
description              : &description "Computer Science PhD Student at UC San Diego"
url                      : https://saviravi.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "saviravi.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "images/headshop.jpg"
  name             : "Savitha Ravi"
  pronouns         : "she/her"  
  bio              : "CS PhD Student at UC San Diego"
  location         : "La Jolla, California"
  employer         : "UC San Diego"
  uri              : # URL
  email            : "s2ravi@ucsd.edu" 
  github           : "saviravi"

publication_category:
  # manuscripts:
  #   title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

include:
  - _pages

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  publications:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

remote_theme: "mmistakes/minimal-mistakes@4.26.2"  # pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-include-cache
